### ISSUE TITLE
Question: DayTrader 7 official source?

### ISSUE THREAD

**Issue by johnjiabinzhang** [WASdev/sample.daytrader7#10]
Hi,
Me and my team are working on maintaining and updating the [DaCapo JVM Benchmark Suite](https://github.com/dacapobench/dacapobench/).

We are trying to update the DayTrader benchmark, and I found this repository on GitHub. I’m wondering where did you get the DayTrader 7 source code from? The only information I can find is still the [DayTrader 3.0 release by Apache Geronimo project](http://geronimo.apache.org/2012/07/13/apache-geronimo-samples-and-daytrader-v300-released.html). Has the benchmark been updated to version 7 since then? Where can I find the official source code?

Thanks for your time and help.

**Comment by jdmcclur** [comment]
Hello, this (daytrader7) is the version we (IBM) use for testing some of the Java EE 7 features. It probably does not have much in common with the DayTrader 3.0 release by Apache Geronimo.

**Comment by johnjiabinzhang** [comment]
So is it right in saying that at some point, even previous of the initial code commit of this repository, you guys have branched off from the Apache DayTrader and deviated quite a lot from it?

**Comment by jdmcclur** [comment]
Yes
