### ISSUE TITLE
JDBC auto-failover cause DayTrader close the connection.

### ISSUE THREAD

**Issue by zhongjiatian** [WASdev/sample.daytrader7#24]
We are trying to use DayTrader as a workload to demonstrate the auto-failover of JDBC connection, to show customers we could auto reroute the SQL request from one data server to another one and would not break the workload.
I tried to add some properties in the JDBC configuration of WLP server (wlp/usr/servers/server1/server.xml):
<dataSource jndiName=“jdbc/TradeDataSource” id=“DefaultDataSource” jdbcDriverRef=“DB2iToolbox” connectionManagerRef=“conMgr1" statementCacheSize=“60” isolationLevel=“TRANSACTION_READ_COMMITTED”> <properties serverName=“9.5.90.216” portNumber=“8471" databaseName=“B1PCC” driverType=“4" user=“dbperf” password=“xxx” **clientRerouteAlternateServerName="9.5.90.59" clientRerouteAlternatePortNumber="8471" enableClientAffinitiesList="1" affinityFailbackInterval="1"**/> </dataSource>
The configuration works well, I saw the expected messages returned from JDBC server side, **the connection has been re-established from 9.5.90.216 to 9.5.90.59**, but it looks the wlp treat the exception as a “fatal” exception and close the connection. How can I configure the WLP to handle this exception and retry the transaction?
Here is the piece of log in the console.log:
[AUDIT   ] J2CA0056I: **The Connection Manager received a fatal connection error from the Resource Adapter for resource jdbc/TradeDataSource**. The exception is: com.ibm.as400.access.AS400JDBCTransientException: A connection failed but has been re-established. Special register settings have been replayed if necessary. Host name or IP address of the connection: 9.5.90.59. Service name or port number of the connection: 8471. (Communication link failure. (A system call received a parameter that is not valid. (Read failed))):java.sql.SQLException: Communication link failure. (A system call received a parameter that is not valid. (Read failed)):java.net.SocketException: A system call received a parameter that is not valid. (Read failed)
[ERROR   ] Error: TradeDirect:getOrders -- error getting user orders

I've double checked with the owner of jt400.jar. He pointed out the jdbc connection has been switched to another system, but return a message SQL4478.  The WAS application should handle this exception and retry the transaction, instead of closing the connection.

**Comment by jdmcclur** [comment]
@zhongjiatian - I assume you are running in JDBC mode? Or is this EJB/JPA mode?

**Comment by jdmcclur** [comment]
@zhongjiatian - what is the status of this one? Do you need my help updating the application to handle the SQLException with -4498 error or is that something you can fork and do yourself? I really don't want to make this the default, but could try to make something custom for you.

**Comment by zhongjiatian** [comment]
@jdmcclur Yes, if you could help, that would be great! A customized version should be enough for me. Thank you!

**Comment by jdmcclur** [comment]
@zhongjiatian - can you try this ear (unzip it first)? If it doesn't work, let me know the stacktrace.

[daytrader7-retry-on-4498-try1.zip](https://github.com/WASdev/sample.daytrader7/files/7583048/daytrader7-retry-on-4498-try1.zip)
