### ISSUE TITLE
[WARNING] Could not transfer metadata io.openliberty:openliberty-kernel/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2): User-specified log class 'org.codehaus.mojo.pluginsupport.logging.DelegatingLog' cannot be found or is not useable.

### ISSUE THREAD

**Issue by alfred4ibm** [WASdev/sample.daytrader7#28]

**Comment by jdmcclur** [comment]
When do you see this? Maybe this is helpful? https://stackoverflow.com/questions/52980706/open-liberty-log-configuration-exception-on-sample-project

**Comment by alfred4ibm** [comment]
hi, yes I had done the same with what I just read in that link. maven 3.5 has this issue, using 3.8 solves it. it happened during man liberty:run. Remember to run "mvn install" after you have the "new" maven in your system, before you run "man liberty:run" again.
