### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by kevarh** [WASdev/sample.daytrader7#3]
# gradle build

FAILURE: Build failed with an exception.
- Where:
  Build file '/root/dt7/sample.daytrader7/daytrader-ee7/build.gradle' line: 59
- What went wrong:
  A problem occurred evaluating project ':daytrader-ee7'.
  
  > Could not find property 'reports' on task ':daytrader-ee7:fvt'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.674 secs
# gradle --version

---
## Gradle 1.4

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_91 (Oracle Corporation 24.91-b01)
OS: Linux 3.13.0-71-generic amd64

**Comment by jdmcclur** [comment]
This is a year old, and I have seen no problems, so closing.
