### ISSUE TITLE
travis build icon on master says "error"

### ISSUE THREAD

**Issue by dshimo** [WASdev/sample.daytrader7#8]
some change introduced 5 months ago caused the build to fail with oraclejdk7
it seems maybe [this commit](https://github.com/WASdev/sample.daytrader7/commit/3e303c85b15d11735944dfbb5e7ab36516316614) might've broke it

EDIT: it's the travis host missing an environment variable

**Comment by stevenschader** [comment]
Hi, what error are you getting? How are you building the project?
steven.

**Comment by dshimo** [comment]
It's not my build. It's the root README.md that contains the travis build badge on the GitHub page

**Comment by stevenschader** [comment]
The error looks like it's on the build host where the jdk7 is no longer valid:
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
this is not related to any changes to the daytrader 7 project.

**Comment by dshimo** [comment]
My mistake, I was premature in my accusation.
I admit this is not an important issue and not related to the daytrader project. I just wanted to bring attention to the travis build badge.

**Comment by cthigh** [comment]
For many of the samples, we removed building with JDK 7 because of the reasons @stevenschader observed. Instead, we started building both Maven and Gradle on Java 8 to verify both worked correctly. See https://github.com/WASdev/sample.servlet/blob/master/.travis.yml as an example.

**Comment by stevenschader** [comment]
I removed the ref to the jdk7
